### ISSUE TITLE
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true

### ISSUE THREAD

**Issue by NeluQi** [MelihAltintas/vue3-openlayers#111]
IconImage.js:102 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

![image](https://user-images.githubusercontent.com/16963395/196655702-e76e4d45-f1d9-414a-bf08-f6bb2b35a687.png)

**Comment by d-koppenhagen** [comment]
Well, this issue came from `ol/style/IconImage.js` (so not from the vue3-openlayers lib). But nonetheless, the Issue has already been tackled and `willReadFrequently` has meanwhile been set to `true` in OpenLayers:
https://github.com/openlayers/openlayers/commit/02f90aebfd488c6918afde4a880bda4c10ad4b00
