### ISSUE TITLE
Roadmap for implementing missing OL features

### ISSUE THREAD

**Issue by christophfriedrich** [MelihAltintas/vue3-openlayers#205]
**Is your feature request related to a problem? Please describe.**
I want to build a reactive map app with Vue and OpenLayers, so I wanted to use this library to make that easier. Now I've discovered that this lib (so far) only supports a certain subset of OL's features, and one I need (namely [ol/source/GeoTIFF](https://openlayers.org/en/latest/apidoc/module-ol_source_GeoTIFF-GeoTIFFSource.html)) is among those that are missing, so my problem is that as of now I can't use this lib.

**Describe the solution you'd like**
vue3-openlayers supporting everything that OL can do.

**Describe alternatives you've considered**
If this lib doesn't support it, I would need to either use OL in Vue directly ([possibly helpful resource I came across](https://dev.to/camptocamp-geo/integrating-an-openlayers-map-in-vue-js-a-step-by-step-guide-2n1p)) or use a different lib. As this seems to be the only project doing OL in Vue3, that might require to downgrade to Vue2, which is not really an option as its LTS is already ending at the end of this year. Of course I could also choose a different reactivity framework or mapping library, but I really like Vue and I expect rather complex mapping requirements in this project, so I'd like to stick to the Vue I know and the OL that has the features.

**Additional context**
Originally, I thought "Okay, this project is still rather new, so stuff is under development, it will only take time until everything's implemented". But then I read @d-koppenhagen stating in #201:

> So in general, vue3-openlayers won't reflect all the features of openlayers 1:1.

So now I'm wondering whether my desired solution is at all the aim of this project :thinking: 

Jumping in and implementing a few things myself _is_ an option for me, but of course I'm thinking twice when I read that the project is not really aiming for full support anyway.

**Comment by d-koppenhagen** [comment]
Hey @christophfriedrich thanks for raising this issue. 
First things first, let me explain my statement a bit, as I think you got me wrong:
> So in general, vue3-openlayers won't reflect all the features of openlayers 1:1.
This statement is only related to the status quo. So of course it would be great to wrap as much as possible from OpenLayers and provide an intuitive declarative API.

To reach this goal, we/I need the help of people using this library by:
- opening separate Issues for missing features
- ideally providing PRs to implement this features
- improving the docs
- raise issues for bugs, etc.
- convince the companies you are working for to let you people contribute

> Jumping in and implementing a few things myself is an option for me, but of course I'm thinking twice when I read that the project is not really aiming for full support anyway.

This sounds great! Again: I hope to support a lot of features of OpenLayers here. Let's start with the requested ones and implement them step-by-step.

Therefore, I will close this issue and I ask you and others too, to open separate Issues for feature request.
There is deliberately no roadmap, since the features are mainly found in this library due to the demand in the form of feature requests.
