### ISSUE TITLE
All texts on map are blurry, the map seems to be compressed

### ISSUE THREAD

**Issue by KevinBazimo** [MelihAltintas/vue3-openlayers#83]
**Texts are blurry**
All texts on map are blurry, the map seems to be compressed, and upper map not loaded correctly.
Is there a way to fix it ?

**To Reproduce**
1. Go to '[demo](https://vue3openlayers.netlify.app/demo/)'
2. Click on Map
3. Scroll to Zoom Out
4. See blurry texts

**Expected behavior**
Have the same map result between vue3-openlayers plugin and OL without plugin

**Screenshots**
OSM with plugin vue3-openlayers:
![image](https://user-images.githubusercontent.com/101792702/173369789-f68a9eb2-757d-41ef-89fe-bc128e4000bb.png)

OSM with wihtout plugin
![image](https://user-images.githubusercontent.com/101792702/173370629-98edf0c4-87a5-41ae-8f8e-7aaf60ca742b.png)

**Comment by MelihAltintas** [comment]
This is related to projection which you used

EPSG:4326 if you change with EPSG:3857 problem will be solved :)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kevin ***@***.***>
Sent: Monday, June 13, 2022 5:02:49 PM
To: MelihAltintas/vue3-openlayers ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MelihAltintas/vue3-openlayers] All texts on map are blurry, the map seems to be compressed (Issue #83)


Texts are blurry
All texts on map are blurry, the map seems to be compressed, is there a way to fix it ?

To Reproduce
Steps to reproduce the behavior:

  1.  Go to 'demo<https://vue3openlayers.netlify.app/demo/>'
  2.  Click on Map
  3.  Scroll to Zoom Out
  4.  See blurry texts

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
OSM with plugin vue3-openlayers:
[image]<https://user-images.githubusercontent.com/101792702/173369789-f68a9eb2-757d-41ef-89fe-bc128e4000bb.png>

OSM with wihtout plugin
[image]<https://user-images.githubusercontent.com/101792702/173370629-98edf0c4-87a5-41ae-8f8e-7aaf60ca742b.png>

**Comment by KevinBazimo** [comment]
Wow, thanks!
I give you a star ^^

**Comment by smbt** [comment]
Does that mean that when the coordinates I´m working with are EPSG:4326 based that I have to live with a blurry and distorted map? Or is it possible/recommended to convert them at runtime into EPSG:3857?

Not sure how to work with the 4326 version since it doesn´t really deliver a satisfactory looking map.

Thanks for any help.
