### ISSUE TITLE
An error will be reported when the autopan property is set for overlay

### ISSUE THREAD

**Issue by sxjyycjt** [MelihAltintas/vue3-openlayers#92]
When I set the attribute autopan of the overlay component to true and click the map to set the coordinates of the overlay, an error will be reported

![bug](https://user-images.githubusercontent.com/37107331/180696623-8cb319a3-8a8e-4ad7-8897-02cc6f300718.png)

**Comment by d-koppenhagen** [comment]
@sxjyycjt the described problem seems not to exist anymore.
I tried it in a Stackblitz playground repo:

https://stackblitz.com/edit/vitejs-vite-bbx95r?file=src%2Fcomponents%2FTheMap.vue

Please re-open and provide some more details for reproduction when the problem still exists.

**Comment by Kevinrp22** [comment]
I have the same problem. @d-koppenhagen  I have tried your example and it seems to work because the 'autopan' prop should be 'autoPan', if you change it the error does appear.

![Captura de pantalla 2023-09-14 125024](https://github.com/MelihAltintas/vue3-openlayers/assets/47866787/ebf30253-6416-4fa5-87e5-f5168f21de82)
